# -*- coding: utf-8 -*-
"""Analysis of given data set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwaizJk_gOqIIO_IQhe6BAJsWUhZy5GI
"""

import pandas as pd
df = pd.read_csv("/content/FuelConsumption (2) (1).csv")
print("First 5 rows of the Dataset: ")
print(df.head())
print ("\ncolumn Names: ")
print(df.columns.tolist())
print("\nShape of the Dataset (rows,columns):", df.shape)
print("\nData Types: ")
print(df.dtypes)

import pandas as pd
df = pd.read_csv("/content/FuelConsumption (2) (1).csv")
print("last 5 rows of the Dataset: ")
print(df.tail())
print ("\ncolumn Names: ")
print(df.columns.tolist())
print("\nShape of the Dataset (rows,columns):", df.shape)
print("\nData Types: ")
print(df.dtypes)