# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWQoSIOzUUvkggv7KJxmf7zPyhL58QSr
"""

#Addtion of numbers

num1 = int(input("Num1: "))
num2 = int(input("Num2: "))
num = num1+num2
print("The sum of two numbers is",num)

#Largest of 4

a = 20
b=200
c = 34
d = 400

if a>b and a>c and a>d:
    print(a)
elif b>a and b>c and b>d:
    print(b)
elif c>a and c>b and c>d:
    print(c)
elif d>a and d>b and d>c:
    print(d)

#Factorial of a number


num1 = int(input("Enter the number: "))
num2 =1
for i in range(1,num1+1,1):
    num2 = i*num2

print("Factorial of",num1,"is",num2)

#EVEN OR ODD

num1 = int(input("Enter the number: "))
if num%2==0:
    print(num1,"is a even number")
else:
    print(num1,"is a odd number")

num1 = int(input("Enter the number: "))

if num1 <= 1:
    print(f"{num1} is not a prime number.")
else:
    for i in range(2, int(num1**0.5) + 1):
        if num1 % i == 0:
            print(f"{num1} is not a prime number.")
            break
    else:
        print(f"{num1} is a prime number.")

#REVERSING A NUMBER

n = 1234
rev = 0
while n > 0:
    digit = n % 10
    rev = rev * 10 + digit
    n = n // 10
print(rev)

#PRINT A PATTERN

n = int(input("Enter the number: " ))
for i in range(1,n+1):
        print(i*"*")

#MULTLIPLICATION TABLE

n = int(input("Enter the table:"))
for i in range (1,11):
    print("1 X",n,"=",n*i)

#CALCULATOR

num1 = int(input("Num1: "))
num2 = int(input("Num2: "))

print("Sum: ",num1+num2)
print("Difference: ",num1-num2)
print("Product: ",num1*num2)
print("Quotient: ",num1/num2)
print('Remainder: ',num1%num2)
print("Exponent: ",num1**num2)

string1 = str(input("Enter the string: "))

if string1==string1[::-1]:
    print("It is Pallindrome")
else:
    print("It is not Pallindrome")